spring:
  rabbitmq:
    host: 192.168.2.100
    port: 5672
    username: admin
    password: 123
    virtual-host: /
    publisher-confirm-type: correlated # 开启消息确认，消息发送到交换机后，成功或失败都会返回一个确认信息
    publisher-returns: true            # 开启消息返回，消息发送到队列失败会返回一个消息
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 使用ant_path_matcher模式。解决报错：Failed to start bean ‘documentationPluginsBootstrapper’
